[2025-10-24T01:45:50.974+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckan_data_etl.load scheduled__2025-10-23T00:00:00+00:00 [queued]>
[2025-10-24T01:45:51.022+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckan_data_etl.load scheduled__2025-10-23T00:00:00+00:00 [queued]>
[2025-10-24T01:45:51.027+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-24T01:45:51.102+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2025-10-23 00:00:00+00:00
[2025-10-24T01:45:51.124+0000] {standard_task_runner.py:57} INFO - Started process 71 to run task
[2025-10-24T01:45:51.141+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ckan_data_etl', 'load', 'scheduled__2025-10-23T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpqvvtxgt7']
[2025-10-24T01:45:51.149+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask load
[2025-10-24T01:45:51.399+0000] {task_command.py:416} INFO - Running <TaskInstance: ckan_data_etl.load scheduled__2025-10-23T00:00:00+00:00 [running]> on host 8f3f5841be05
[2025-10-24T01:45:51.541+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ckan_data_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-23T00:00:00+00:00'
[2025-10-24T01:45:51.672+0000] {logging_mixin.py:154} INFO - Success: Loaded 63 records to recalls_db.ckan_visitors table.
[2025-10-24T01:45:51.673+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-10-24T01:45:51.689+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ckan_data_etl, task_id=load, execution_date=20251023T000000, start_date=20251024T014550, end_date=20251024T014551
[2025-10-24T01:45:51.757+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-24T01:45:51.783+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
